Create reverse proxy for swagger to be able to use "try out" button f…
wilhelm-lab/dlomix-serving pull request #34
Opened 2023-02-23 20:57 UTC by dulguunb

…or triton

since triton does not support CORS

2023-03-29 13:26 UTC, LLautenbacher requested changes

2023-03-31 19:17 UTC, dulguunb commented on docker-compose.yml
> +      - 8505:8501
if we want a request from outside for instance swagger, we would need to have an exposed port right?

2023-03-31 19:47 UTC, dulguunb commented on docker-compose.yml
> +      - 8505:8501
okay, just checked even without it, it works. Removed the lines

2023-03-31 19:47 UTC, dulguunb commented on docker-compose.yml
> -     - .env
I think it was a mistake that i removed, I put them back

2023-03-31 19:48 UTC, dulguunb commented on docker-compose.yml
> +      - serving
the depedency_on: healthy works. So I removed the pinging

2023-03-31 19:48 UTC, dulguunb commented on docker-compose.yml
> +        cd /workspace/swagger
Added two dockerfiles

2023-03-31 19:48 UTC, dulguunb commented on swagger/README.md
> +`Swagger.yaml` generation is a service that runs before serving of the Swagger. This service waits until the Triton and Reverse proxy servers are up and running. There is a logic in the script where
yeah it was possible, I added the check and removed the info from readme

2023-03-31 19:48 UTC, dulguunb commented on swagger/README.md
> +# Input boilerplate
fixed

2023-03-31 19:49 UTC, dulguunb commented on swagger/swagger_gen.py
> +    print(model_names[0])
changed

2023-03-31 19:49 UTC, dulguunb commented on swagger/swagger_gen.py
> +            time.sleep(wait_time)
removed the those lines

2023-04-03 08:28 UTC, LLautenbacher commented on docker-compose.yml
> +      - 8505:8501
Not sure what you tested, the swagger service is also configured in the docker-compose file, so it is also in the docker network.

2023-04-03 08:38 UTC, LLautenbacher commented on docker-compose.yml
> +        cd /workspace/swagger
You can define multiple stages in one Dockerfile and refer to them later on. You can see an example of that in the main [Dockerfile](https://github.com/wilhelm-lab/dlomix-serving/blob/main/Dockerfile). I read somewhere that this is preferred over multiple Dockerfiles let, me know if you find something that says differently!

2023-04-04 19:10 UTC, dulguunb commented on docker-compose.yml
> +        cd /workspace/swagger
true, changed the code

2023-04-04 19:32 UTC, dulguunb commented
I put the waiting logic again and exposed grpc port:
 - the healthy status does not always work so we need to have some logic that waits
 - without grpc port exposing, we would not be able to use grpc code from outside

2023-04-04 19:32 UTC, dulguunb commented on swagger/swagger_gen.py
> +            time.sleep(wait_time)
I put them back again and in separate function because health status sometimes lies

2023-04-11 14:19 UTC, LLautenbacher approved these changes

2023-04-11 14:20 UTC, merged